/* Generated By:JavaCC: Do not edit this line. NewScriptTreeConstants.java Version 6.0_1 */
package org.immregistries.dqa.message_modifier.script;

import org.immregistries.dqa.message_modifier.script.*;

public interface NewScriptTreeConstants
{
  public int JJTEXPRESSIONS = 0;
  public int JJTCOMMAND = 1;
  public int JJTUSE_COMMAND = 2;
  public int JJTASSIGNMENT = 3;
  public int JJTIF = 4;
  public int JJTCOMP = 5;
  public int JJTFOR = 6;
  public int JJTREF_POINTER = 7;
  public int JJTREFERENCE = 8;
  public int JJTREF_CONTEXT = 9;
  public int JJTREF_ID = 10;
  public int JJTFUNCTION = 11;
  public int JJTARGS = 12;
  public int JJTSTATEMENT = 13;
  public int JJTSEG_ID = 14;
  public int JJTFIELD_NUM = 15;
  public int JJTSUB_NUM = 16;
  public int JJTREPETION_SELECTOR = 17;
  public int JJTCOMMENTS = 18;


  public String[] jjtNodeName = {
    "EXPRESSIONS",
    "COMMAND",
    "USE_COMMAND",
    "ASSIGNMENT",
    "IF",
    "COMP",
    "FOR",
    "REF_POINTER",
    "REFERENCE",
    "REF_CONTEXT",
    "REF_ID",
    "FUNCTION",
    "ARGS",
    "STATEMENT",
    "SEG_ID",
    "FIELD_NUM",
    "SUB_NUM",
    "REPETION_SELECTOR",
    "COMMENTS",
  };
}
/* JavaCC - OriginalChecksum=b244ab6b1569eb894312f3224b0d4176 (do not edit this line) */
