package org.immregistries.dqa.message_modifier.script;

import org.immregistries.dqa.message_modifier.transform.ReferenceParsed;
import org.immregistries.dqa.message_modifier.transform.SetCommand;

/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 6.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SimpleNode implements Node {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected NewScript parser;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(NewScript p, int i) {
    this(i);
    parser = p;
  }

  public void testPrint() {
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        System.out.println("Node : " + n.toString());
        System.out.println("Value : [" + n.value + "]");
        if (n != null) {
          n.testPrint();
        }
      }
    }
  }

  public SetCommand createSetCommand() {
	  SetCommand command = new SetCommand();
	  for (int i = 0; i < children.length; ++i) {
		  SimpleNode n = (SimpleNode)children[i];
		  if(n.id == 1) {
			  SimpleNode child = (SimpleNode) n.children[0];
			  switch(child.id) {
              	case 3:
              		ReferenceParsed reference = new ReferenceParsed();
              		SimpleNode refId = (SimpleNode) child.children[0].jjtGetChild(0);
                    SimpleNode segId = (SimpleNode) refId.children[0];
                    reference.setSegment((String) segId.value);
                    SimpleNode fieldNum = (SimpleNode) refId.children[1];
                    reference.setField((int) fieldNum.value);
                    SimpleNode statement = (SimpleNode) child.children[1];
                    command.setStringValue((String) statement.value);
                    command.setTargetReference(reference);
              		break;
              		
              	default:
              		command = null;
              		break;
			  }
		  }
	  }
	  return command;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() {
    return NewScriptTreeConstants.jjtNodeName[id];
  }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        System.out.println("[" + n.value + "]");
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }
  }

  public int getId() {
    return id;
  }
}

/* JavaCC - OriginalChecksum=c92004f860c88d391c641c1b89b5f8b1 (do not edit this line) */

