/* Generated By:JJTree&JavaCC: Do not edit this line. NewScriptConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NewScriptConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 4;
  /** RegularExpression Id. */
  int FOR = 5;
  /** RegularExpression Id. */
  int THEN = 6;
  /** RegularExpression Id. */
  int USE = 7;
  /** RegularExpression Id. */
  int CALL = 8;
  /** RegularExpression Id. */
  int ID = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int NUM = 11;
  /** RegularExpression Id. */
  int PRESET_VALUE = 12;
  /** RegularExpression Id. */
  int UNQUOTED_STRING = 13;
  /** RegularExpression Id. */
  int CONTEXT_SELECTOR = 14;
  /** RegularExpression Id. */
  int EQUAL = 15;
  /** RegularExpression Id. */
  int DIFFERENT = 16;
  /** RegularExpression Id. */
  int GREATER_THAN = 17;
  /** RegularExpression Id. */
  int LESSER_THAN = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"if\"",
    "\"for\"",
    "\"then\"",
    "\"use\"",
    "\"call\"",
    "<ID>",
    "<STRING>",
    "<NUM>",
    "<PRESET_VALUE>",
    "<UNQUOTED_STRING>",
    "\"::\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\";\"",
    "\"\\n\"",
    "\"=\"",
    "\"$\"",
    "\"-\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"=>\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
  };

}
